# Generated by Django 3.2.9 on 2022-01-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('corp_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('corp_name', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
